version: '3.3'
services:
  t4tocs:
    build: 
      context: .
      dockerfile: dotnet_dockerfile
    volumes:
      - type: bind
        source: ../src/
        target: /source
    tty: true
